# Generated by Django 4.0.1 on 2022-08-02 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_author_options_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='name',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.language'),
        ),
        migrations.AddField(
            model_name='language',
            name='languages',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
